[build]
  publish = "public"      # Folder tempat file HTML berada
  functions = "functions" # Folder tempat kode Python berada

[functions]
  node_bundle = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200